'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    //     await queryInterface.bulkInsert(
    //       'Event',
    //       [
    //         {
    //           id: 1,
    //           supervisorId: 1,
    //           eventName: 'Damascus Music Festival',
    //           mainPhoto: 'http://207.180.217.5:5000/events/damascus_music_festival_main.jpg',
    //           miniPoster: 'http://207.180.217.5:5000/events/damascus_music_festival_mini.jpg',
    //           eventPhotos: [
    //             'http://207.180.217.5:5000/events/damascus_music_festival_1.jpg',
    //             'http://207.180.217.5:5000/events/damascus_music_festival_2.jpg',
    //           ],
    //           eventType: 1,
    //           startEventDate: new Date('2025-09-01T00:00:00Z'),
    //           endEventDate: new Date('2025-09-02T00:00:00Z'),
    //           startApplyDate: new Date('2025-08-22T00:00:00Z'),
    //           endApplyDate: new Date('2025-08-30T00:00:00Z'),
    //           startEventHour: '7:00 PM',
    //           endEventHour: '10:00 PM',
    //           province: 1,
    //           location: 'Damascus Opera House',
    //           ticketOptionsAndPrices: `{
    //             "vip": { "price": 50000, "description": "Premium seating with exclusive access" },
    //             "classic": { "price": 25000, "description": "Standard seating" }
    //           }`,
    //           attendanceType: 'any',
    //           seatsQty: 500,
    //           availableTickets: 500,
    //           description: 'A vibrant music festival featuring top Syrian artists.',
    //           notes: 'Bring ID for entry.',
    //           eventStatus: 'commingSoon',
    //           needApproveFromSupervisor: true,
    //           visitCount: 0,
    //           isApproved: true,
    //           isDeclined: false,
    //           isVisible: true,
    //           createdAt: new Date('2025-04-23T00:00:00Z'),
    //           updatedAt: new Date('2025-04-23T00:00:00Z'),
    //         },
    //         {
    //           id: 2,
    //           supervisorId: 2,
    //           eventName: 'Aleppo Art Exhibition',
    //           mainPhoto: 'http://207.180.217.5:5000/events/aleppo_art_exhibition_main.jpg',
    //           miniPoster: 'http://207.180.217.5:5000/events/aleppo_art_exhibition_mini.jpg',
    //           eventPhotos: ['http://207.180.217.5:5000/events/aleppo_art_exhibition_1.jpg'],
    //           eventType: 2,
    //           startEventDate: new Date('2025-06-01T00:00:00Z'),
    //           endEventDate: new Date('2025-06-03T00:00:00Z'),
    //           startApplyDate: new Date('2025-04-15T00:00:00Z'),
    //           endApplyDate: new Date('2025-05-31T00:00:00Z'),
    //           startEventHour: '10:00 AM',
    //           endEventHour: '6:00 PM',
    //           province: 3,
    //           location: 'Aleppo Cultural Center',
    //           ticketOptionsAndPrices: `{
    //             "economy": { "price": 10000, "description": "General admission" }
    //           }`,
    //           attendanceType: 'any',
    //           seatsQty: 200,
    //           availableTickets: 200,
    //           description: 'Showcasing contemporary Syrian art and sculptures.',
    //           notes: 'Free entry for students with ID.',
    //           eventStatus: 'commingSoon',
    //           needApproveFromSupervisor: false,
    //           visitCount: 0,
    //           isApproved: false,
    //           isDeclined: false,
    //           isVisible: true,
    //           createdAt: new Date('2025-04-24T00:00:00Z'),
    //           updatedAt: new Date('2025-04-24T00:00:00Z'),
    //         },
    //         {
    //           id: 3,
    //           supervisorId: 3,
    //           eventName: 'Latakia Film Festival',
    //           mainPhoto: 'http://207.180.217.5:5000/events/latakia_film_festival_main.jpg',
    //           miniPoster: 'http://207.180.217.5:5000/events/latakia_film_festival_mini.jpg',
    //           eventPhotos: [
    //             'http://207.180.217.5:5000/events/latakia_film_festival_1.jpg',
    //             'http://207.180.217.5:5000/events/latakia_film_festival_2.jpg',
    //           ],
    //           eventType: 3,
    //           startEventDate: new Date('2025-07-10T00:00:00Z'),
    //           endEventDate: new Date('2025-07-12T00:00:00Z'),
    //           startApplyDate: new Date('2025-03-20T00:00:00Z'),
    //           endApplyDate: new Date('2025-07-09T00:00:00Z'),
    //           startEventHour: '6:00 PM',
    //           endEventHour: '11:00 PM',
    //           province: 6,
    //           location: 'Latakia Cinema Hall',
    //           ticketOptionsAndPrices: `{
    //             "vip": { "price": 40000, "description": "Priority seating and Q&A with filmmakers" },
    //             "economy": { "price": 15000, "description": "Standard seating" }
    //           }`,
    //           attendanceType: 'any',
    //           seatsQty: 300,
    //           availableTickets: 300,
    //           description: 'A celebration of regional and international cinema.',
    //           notes: 'Arrive 30 minutes early for seating.',
    //           eventStatus: 'commingSoon',
    //           needApproveFromSupervisor: true,
    //           visitCount: 0,
    //           isApproved: false,
    //           isDeclined: false,
    //           isVisible: true,
    //           createdAt: new Date('2025-04-25T00:00:00Z'),
    //           updatedAt: new Date('2025-04-25T00:00:00Z'),
    //         },
    //         {
    //           id: 4,
    //           supervisorId: 1,
    //           eventName: 'Homs Food Festival',
    //           mainPhoto: 'http://207.180.217.5:5000/events/homs_food_festival_main.jpg',
    //           miniPoster: 'http://207.180.217.5:5000/events/homs_food_festival_mini.jpg',
    //           eventPhotos: ['http://207.180.217.5:5000/events/homs_food_festival_1.jpg'],
    //           eventType: 4,
    //           startEventDate: new Date('2025-08-15T00:00:00Z'),
    //           endEventDate: new Date('2025-08-16T00:00:00Z'),
    //           startApplyDate: new Date('2025-07-25T00:00:00Z'),
    //           endApplyDate: new Date('2025-08-14T00:00:00Z'),
    //           startEventHour: '12:00 PM',
    //           endEventHour: '8:00 PM',
    //           province: 2,
    //           location: 'Homs Central Park',
    //           ticketOptionsAndPrices: `{
    //             "classic": { "price": 20000, "description": "Access to all food stalls" }
    //           }`,
    //           attendanceType: 'any',
    //           seatsQty: 1000,
    //           availableTickets: 1000,
    //           description: 'Explore culinary delights from local and regional chefs.',
    //           notes: 'No outside food allowed.',
    //           eventStatus: 'commingSoon',
    //           needApproveFromSupervisor: false,
    //           visitCount: 0,
    //           isApproved: false,
    //           isDeclined: false,
    //           isVisible: true,
    //           createdAt: new Date('2025-04-26T00:00:00Z'),
    //           updatedAt: new Date('2025-04-26T00:00:00Z'),
    //         },
    //         {
    //           id: 5,
    //           supervisorId: 2,
    //           eventName: 'Tartous Beach Concert',
    //           mainPhoto: 'http://207.180.217.5:5000/events/tartous_beach_concert_main.jpg',
    //           miniPoster: 'http://207.180.217.5:5000/events/tartous_beach_concert_mini.jpg',
    //           eventPhotos: [
    //             'http://207.180.217.5:5000/events/tartous_beach_concert_1.jpg',
    //             'http://207.180.217.5:5000/events/tartous_beach_concert_2.jpg',
    //           ],
    //           eventType: 1,
    //           startEventDate: new Date('2025-09-01T00:00:00Z'),
    //           endEventDate: new Date('2025-09-01T00:00:00Z'),
    //           startApplyDate: new Date('2025-08-10T00:00:00Z'),
    //           endApplyDate: new Date('2025-08-31T00:00:00Z'),
    //           startEventHour: '8:00 PM',
    //           endEventHour: '11:00 PM',
    //           province: 5,
    //           location: 'Tartous Beach Arena',
    //           ticketOptionsAndPrices: `{
    //             "vip": { "price": 60000, "description": "Front-row experience with VIP lounge" },
    //             "classic": { "price": 30000, "description": "General admission with seating" },
    //             "economy": { "price": 12000, "description": "Standing area access" }
    //           }`,
    //           attendanceType: 'any',
    //           seatsQty: 800,
    //           availableTickets: 800,
    //           description: 'A beachside concert featuring popular regional bands.',
    //           notes: 'Dress code: Casual beach attire.',
    //           eventStatus: 'commingSoon',
    //           needApproveFromSupervisor: true,
    //           visitCount: 0,
    //           isApproved: false,
    //           isDeclined: false,
    //           isVisible: true,
    //           createdAt: new Date('2025-04-27T00:00:00Z'),
    //           updatedAt: new Date('2025-04-27T00:00:00Z'),
    //         },
    //       ],
    //       {},
    //     );
    //     await queryInterface.sequelize.query(`SELECT setval('"Event_id_seq"', (SELECT MAX(id) FROM "Event"));`);
  },

  async down(queryInterface, Sequelize) {
    try {
      await queryInterface.bulkDelete('Event', null, { paranoid: false });
    } catch (error) {
      console.error('Error in down function:', error);
      throw error;
    }
  },
};
